import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

test("verifier release workflow keeps release-gate dispatch, upload metadata backfill, and CI triage paths stable", async () => {
  const workflowPath = path.resolve(".github/workflows/verifier-release-gate.yml");
  const workflow = await fs.readFile(workflowPath, "utf8");

  assert.match(workflow, /^name: verifier-release-gate/m);
  assert.match(workflow, /^on:\n  workflow_dispatch:/m);
  assert.match(workflow, /schedule:\n\s+- cron: "0 3 \* \* \*"/m);
  assert.match(workflow, /\n  pull_request:\n/m);
  assert.doesNotMatch(workflow, /pull_request_target:/);
  assert.match(workflow, /baseline:/);
  assert.match(workflow, /baseline_target:/);
  assert.match(workflow, /policy:/);
  assert.match(workflow, /artifact_retention_days:/);
  assert.match(workflow, /github_live_mutation:/);
  assert.match(workflow, /permissions:\n  contents: read\n  checks: write/m);
  assert.match(workflow, /npm ci/);
  assert.match(workflow, /npm run typecheck/);
  assert.match(workflow, /npm run build/);
  assert.match(workflow, /npm test/);
  assert.match(workflow, /dist\/cli\.mjs\s+eval\s+verification/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+baselines\s+json/s);
  assert.match(workflow, /--write-artifact/);
  assert.match(workflow, /--write-bundle/);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+handoff\s+latest\s+--cwd/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+triage\s+summary\s+latest\s+--cwd/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+promotion\s+plan/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+checks\s+export\s+latest\s+--cwd.*--github-actions/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+checks\s+summary\s+latest\s+summary.*--github-actions/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+triage\s+summary\s+latest\s+summary.*--github-actions/s);
  assert.match(workflow, /MJ_VERIFIER_GITHUB_LIVE_MUTATION/);
  assert.match(workflow, /Apply optional live GitHub check run mutation/);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+github\s+apply\s+latest\s+summary.*--github-actions/s);
  assert.match(workflow, /dist\/cli\.mjs\s+verifier\s+github\s+result\s+latest\s+summary/s);
  assert.match(workflow, /GITHUB_TOKEN: \$\{\{ github\.token \}\}/);
  assert.match(workflow, /MJ_VERIFIER_UPLOAD_ARTIFACT_ID:/);
  assert.match(workflow, /MJ_VERIFIER_UPLOAD_ARTIFACT_URL:/);
  assert.match(workflow, /MJ_VERIFIER_UPLOAD_ARTIFACT_DIGEST:/);
  assert.match(workflow, /artifact-id/);
  assert.match(workflow, /artifact-url/);
  assert.match(workflow, /artifact-digest/);
  assert.match(workflow, /::\$\{level\}/);
  assert.match(workflow, /\$GITHUB_STEP_SUMMARY/);
  assert.match(workflow, /actions\/upload-artifact@v4/);
  assert.match(workflow, /Upload verifier automation artifacts/);
  assert.match(workflow, /Upload verifier metadata backfill/);
  assert.match(workflow, /retention-days:/);
  assert.match(workflow, /\.mj-code\/ci/);
  assert.match(workflow, /\.mj-code\/verifier-inspect/);
  assert.match(workflow, /verifier-handoff\.json/);
  assert.match(workflow, /verifier-triage\.json/);
  assert.match(workflow, /verifier-checks\.json/);
  assert.match(workflow, /verifier-github-mutation\.json/);
  assert.match(workflow, /verifier-promotion-plan\.pre-upload\.json/);
});
